Feat: create news scraper
UniversityOfGdanskProjects/API-KIOSK pull request #49
Opened 2023-03-12 13:18 UTC by amordzon

## Description
Create a web scraper for news. It should get news from https://inf.ug.edu.pl/news, https://inf.ug.edu.pl/studinfo and https://mfi.ug.edu.pl/wydzial/aktualnosci, https://mfi.ug.edu.pl/wydzial/aktualnosci/archiwum-aktualnosci. It should get info including title, short and long description, date, photo and site.

## Clickup Ticket
https://app.clickup.com/t/38g19hz

2023-03-12 13:55 UTC, jzapiorkowski commented on src/Controllers/news.controller.ts
> +    res: Response
add types for req and res

2023-03-12 13:55 UTC, jzapiorkowski commented on src/Controllers/news.controller.ts
> +        const singleNews = await NewsModel.findOne({ _id: id });
return news without __v value

2023-03-12 13:55 UTC, jzapiorkowski commented on src/Controllers/news.controller.ts
> +        const news = await NewsModel.find({});
return news without __v value

2023-03-12 13:55 UTC, jzapiorkowski commented on src/Controllers/news.controller.ts
> +        return res.json({ singleNews: singleNews });
```suggestion
        return res.json(singleNews);
```

2023-03-12 13:55 UTC, jzapiorkowski commented on src/Models/news.model.ts
> +    site: {
wouldn't it be more explicit to name it something like `source`?

2023-03-12 13:55 UTC, jzapiorkowski commented on src/Schedulers/news.scheduler.ts
> +        console.log('News updated');
remove console log

2023-03-12 13:55 UTC, jzapiorkowski commented on src/Services/newsScraper.service.ts
> +const getNewsInCategoriessMFI = async (site: string) => {
add return type

2023-03-12 13:55 UTC, jzapiorkowski commented on src/Services/newsScraper.service.ts
> +    return newsArray;
wrap this funtion in try catch block

2023-03-12 13:55 UTC, jzapiorkowski commented on src/Services/newsScraper.service.ts
> +const getNewsInCategoriesINF = async (site: string) => {
add return type

2023-03-12 13:55 UTC, jzapiorkowski commented on src/Services/newsScraper.service.ts
> +    return newsArray;
wrap function in try catch block

2023-03-12 13:55 UTC, jzapiorkowski commented on src/Types/News.type.ts
> +export enum NewsCategoryEnum {
```suggestion
export enum NewsCategory {
```

2023-03-12 13:55 UTC, jzapiorkowski commented on src/index.ts
> +const PORT = process.env.PORT || 3000;
```suggestion
const PORT = process.env.PORT || 3001;
```

2023-03-12 13:55 UTC, jzapiorkowski commented on src/utils/newsScraper/fixDate.ts
> +export const reformatDate = (dateStr: string) => {
add return type

2023-03-12 13:55 UTC, jzapiorkowski commented on src/utils/newsScraper/removeSeeMore.ts
> +    let newText = text.replace(regex, '...');
```suggestion
    const regex = /... więcej$/;
    const newText = text.replace(regex, '...');
```

2023-03-12 13:55 UTC, jzapiorkowski commented on src/utils/newsScraper/returnCategoryEnum.ts
> +export const returnCategoryEnum = (category: string): NewsCategoryEnum => {
```suggestion
export const mapNewsCategory = (category: string): NewsCategory => {
```

2023-03-12 13:55 UTC, jzapiorkowski commented on src/utils/newsScraper/splitByLines.ts
> +};
```suggestion
import { parseHTMLInText } from '../parseHTMLInText';

export const splitByLines = (text: string): string[] => {
    const newText = text.trim().split(/\r?\n+/);
    const parsedText = newText.map((line) => parseHTMLInText(line));
    
    return parsedText;
};
```

2023-03-12 13:55 UTC, jzapiorkowski commented on src/Services/newsScraper.service.ts
> +        const newsMFIArray: News[][] = await Promise.all(
I think it would be better to use `Promise.allSettled` Here

2023-03-12 20:03 UTC, jzapiorkowski requested changes
LGTM

2023-03-12 20:03 UTC, jzapiorkowski commented on src/Services/newsScraper.service.ts
> +                let shortDescription = removeSeeMore(body);
```suggestion
                const shortDescription = removeSeeMore(body);
```

2023-03-13 09:41 UTC, amordzon commented on src/Services/newsScraper.service.ts
> +    return newsArray;
pierdol sie

2023-03-13 09:42 UTC, amordzon commented on src/Services/newsScraper.service.ts
> +    return newsArray;
jw

2023-03-14 15:31 UTC, jzapiorkowski approved these changes

2023-03-14 15:31 UTC, jzapiorkowski commented on src/Controllers/news.controller.ts
> +    req: Request,
add `id` to request params type

2023-03-27 07:52 UTC, merged